--- #YAML:1.0
name: Proc-Fork
version: 0.3
author:
  - Aristotle Pagaltzis <pagaltzis@gmx.de>
abstract: Simple, intuitive interface to the fork() system call
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
