---
name: Proc-Fork
version: 0.5
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
abstract: 'Simple, intuitive interface to the fork() system call'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Proc::Fork:
    file: lib/Proc/Fork.pm
    version: 0.5
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
