---
name: Proc-Fork
version: 0.2
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
abstract: 'Simple, intuitive interface to the fork() system call'
license: perl
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Proc::Fork:
    file: lib/Proc/Fork.pm
    version: 0.2
generated_by: Module::Build version 0.2611
